import type { Metadata } from 'next'
import Link from 'next/link'
import { createServiceClient } from '@/lib/supabase/service'

type Gap = {
  title: string
  description: string
  priority: 'high' | 'medium' | 'low'
  suggestedKeyword: string
}

type ContentAuditResult = {
  gaps: Gap[]
  topicClusters: unknown[]
  quickWins: string[]
  pageCount: number
}

const playfair: React.CSSProperties = { fontFamily: 'var(--font-playfair, "Playfair Display", serif)' }

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>
}): Promise<Metadata> {
  const { token } = await params
  const supabase = createServiceClient()
  const { data } = await supabase
    .from('audit_results')
    .select('domain')
    .eq('share_token', token)
    .single()

  const domain = data?.domain ?? 'your site'
  return {
    title: `SEO Report for ${domain} — Byline`,
    description: `Content gap audit report for ${domain} generated by Byline.`,
  }
}

export default async function ReportPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const supabase = createServiceClient()

  const { data, error } = await supabase
    .from('audit_results')
    .select('id, domain, result, created_at, url')
    .eq('share_token', token)
    .single()

  if (error || !data) {
    return (
      <div style={{ background: '#FDFAF6', minHeight: '100vh', color: '#1C1917' }}>
        {/* Header */}
        <nav style={{ background: '#FDFAF6', borderBottom: '1px solid #E7E0D6', padding: '0 24px' }}>
          <div style={{ maxWidth: 960, margin: '0 auto', height: 56, display: 'flex', alignItems: 'center' }}>
            <Link href="/">
              <span style={{ ...playfair, fontSize: 22, fontWeight: 900, color: '#B87333', letterSpacing: '-0.01em' }}>
                byline<span style={{ color: '#1C1917' }}>.</span>
              </span>
            </Link>
          </div>
        </nav>
        <div style={{ maxWidth: 640, margin: '80px auto', padding: '0 24px', textAlign: 'center' }}>
          <h1 style={{ ...playfair, fontSize: 32, fontWeight: 700, color: '#1C1917', marginBottom: 16 }}>
            Report not found
          </h1>
          <p style={{ fontSize: 16, color: '#57534E', marginBottom: 32 }}>
            This report link may have expired or the URL is incorrect.
          </p>
          <Link
            href="/audit"
            style={{
              display: 'inline-block',
              background: '#B87333',
              color: '#fff',
              padding: '12px 24px',
              borderRadius: 12,
              fontWeight: 600,
              fontSize: 15,
              textDecoration: 'none',
            }}
          >
            Run a new audit →
          </Link>
        </div>
      </div>
    )
  }

  const result = data.result as ContentAuditResult | null
  const domain = data.domain ?? 'your site'
  const gaps: Gap[] = result?.gaps ?? []
  const quickWins: string[] = result?.quickWins ?? []
  const pageCount: number = result?.pageCount ?? 0
  const highPriorityCount = gaps.filter((g) => g.priority === 'high').length
  const auditDate = new Date(data.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <div style={{ background: '#FDFAF6', minHeight: '100vh', color: '#1C1917' }}>
      {/* Header */}
      <nav style={{ background: '#FDFAF6', borderBottom: '1px solid #E7E0D6', padding: '0 24px', position: 'sticky', top: 0, zIndex: 50 }}>
        <div style={{ maxWidth: 960, margin: '0 auto', height: 56, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link href="/">
            <span style={{ ...playfair, fontSize: 22, fontWeight: 900, color: '#B87333', letterSpacing: '-0.01em' }}>
              byline<span style={{ color: '#1C1917' }}>.</span>
            </span>
          </Link>
          <span style={{ fontSize: 13, color: '#57534E' }}>SEO Audit Report</span>
        </div>
      </nav>

      {/* Report body */}
      <main style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px 80px' }}>

        {/* Domain + summary */}
        <div style={{ marginBottom: 40 }}>
          <p style={{ fontSize: 12, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.18em', color: '#B87333', marginBottom: 12 }}>
            Content Gap Report
          </p>
          <h1 style={{ ...playfair, fontSize: 36, fontWeight: 700, color: '#1C1917', marginBottom: 8, lineHeight: 1.1 }}>
            {domain}
          </h1>
          <p style={{ fontSize: 14, color: '#57534E', marginBottom: 24 }}>
            Audited on {auditDate} · {pageCount} pages scanned
          </p>

          {/* Score summary cards */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12 }}>
            <div style={{ background: '#fff', border: '1px solid #E7E0D6', borderRadius: 12, padding: '16px 20px' }}>
              <p style={{ fontSize: 28, fontWeight: 700, color: '#B87333', margin: 0 }}>{gaps.length}</p>
              <p style={{ fontSize: 13, color: '#57534E', margin: '4px 0 0' }}>Content Gaps</p>
            </div>
            <div style={{ background: '#fff', border: '1px solid #E7E0D6', borderRadius: 12, padding: '16px 20px' }}>
              <p style={{ fontSize: 28, fontWeight: 700, color: '#1C1917', margin: 0 }}>{highPriorityCount}</p>
              <p style={{ fontSize: 13, color: '#57534E', margin: '4px 0 0' }}>High Priority</p>
            </div>
            <div style={{ background: '#fff', border: '1px solid #E7E0D6', borderRadius: 12, padding: '16px 20px' }}>
              <p style={{ fontSize: 28, fontWeight: 700, color: '#1C1917', margin: 0 }}>{quickWins.length}</p>
              <p style={{ fontSize: 13, color: '#57534E', margin: '4px 0 0' }}>Quick Wins</p>
            </div>
          </div>
        </div>

        {/* Quick wins */}
        {quickWins.length > 0 && (
          <section style={{ marginBottom: 40 }}>
            <h2 style={{ ...playfair, fontSize: 22, fontWeight: 700, color: '#1C1917', marginBottom: 16 }}>
              Quick Wins
            </h2>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
              {quickWins.map((win, i) => (
                <li
                  key={i}
                  style={{
                    display: 'flex',
                    alignItems: 'flex-start',
                    gap: 10,
                    padding: '10px 0',
                    borderBottom: i < quickWins.length - 1 ? '1px solid #E7E0D6' : 'none',
                  }}
                >
                  <span style={{ color: '#B87333', fontWeight: 700, fontSize: 15, marginTop: 1, flexShrink: 0 }}>✓</span>
                  <span style={{ fontSize: 15, color: '#1C1917', lineHeight: 1.5 }}>{win}</span>
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* Content gaps as action items */}
        {gaps.length > 0 && (
          <section style={{ marginBottom: 48 }}>
            <h2 style={{ ...playfair, fontSize: 22, fontWeight: 700, color: '#1C1917', marginBottom: 16 }}>
              Action Items
            </h2>
            <p style={{ fontSize: 14, color: '#57534E', marginBottom: 20 }}>
              Each item below is a specific article you should write. High-priority gaps represent the biggest opportunities.
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {gaps.map((gap, i) => (
                <div
                  key={i}
                  style={{
                    background: '#fff',
                    border: '1px solid #E7E0D6',
                    borderRadius: 12,
                    padding: '16px 20px',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 8 }}>
                    <h3 style={{ fontSize: 15, fontWeight: 600, color: '#1C1917', margin: 0, flex: 1 }}>
                      Write an article targeting &ldquo;{gap.suggestedKeyword || gap.title}&rdquo;
                    </h3>
                    {gap.priority === 'high' && (
                      <span
                        style={{
                          fontSize: 11,
                          fontWeight: 600,
                          padding: '2px 8px',
                          borderRadius: 999,
                          background: 'rgba(184,115,51,0.12)',
                          color: '#9A6228',
                          flexShrink: 0,
                          marginTop: 2,
                        }}
                      >
                        High Priority
                      </span>
                    )}
                    {gap.priority === 'medium' && (
                      <span
                        style={{
                          fontSize: 11,
                          fontWeight: 600,
                          padding: '2px 8px',
                          borderRadius: 999,
                          background: 'rgba(217,119,6,0.1)',
                          color: '#b45309',
                          flexShrink: 0,
                          marginTop: 2,
                        }}
                      >
                        Medium
                      </span>
                    )}
                  </div>
                  <p style={{ fontSize: 14, color: '#57534E', margin: '0 0 8px', lineHeight: 1.5 }}>
                    {gap.description}
                  </p>
                  <p style={{ fontSize: 13, color: '#B87333', fontWeight: 500, margin: 0 }}>
                    Topic: {gap.title}
                  </p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Footer CTA */}
        <div
          style={{
            background: '#1C1917',
            borderRadius: 16,
            padding: '32px',
            textAlign: 'center',
          }}
        >
          <h2
            style={{
              ...playfair,
              fontSize: 22,
              fontWeight: 700,
              color: '#F7F3EC',
              marginBottom: 12,
            }}
          >
            Want Byline to write these articles for you?
          </h2>
          <p style={{ fontSize: 15, color: '#A89070', marginBottom: 24, lineHeight: 1.6 }}>
            Byline generates publish-ready, SEO-optimized articles from your content gaps — in your brand voice, in minutes.
          </p>
          <Link
            href="/pricing"
            style={{
              display: 'inline-block',
              background: '#B87333',
              color: '#fff',
              padding: '14px 28px',
              borderRadius: 12,
              fontWeight: 600,
              fontSize: 15,
              textDecoration: 'none',
            }}
          >
            See plans →
          </Link>
        </div>
      </main>
    </div>
  )
}
