import type { Metadata } from 'next'
import Link from 'next/link'
import { createServiceClient } from '@/lib/supabase/service'
import { TwoScoreSection } from '@/components/audit/TwoScoreSection'

// ── Types ─────────────────────────────────────────────────────────────────────

type Gap = {
  title: string
  description: string
  priority: 'high' | 'medium' | 'low'
  suggestedKeyword: string
}

type ContentAuditResult = {
  gaps: Gap[]
  topicClusters: unknown[]
  quickWins: string[]
  pageCount: number
}

type GeoFactor = {
  name: string
  score: number
  maxScore: number
  status: 'good' | 'needs-work' | 'missing' | 'unverified'
  /** False when the factor could not be assessed; excluded from the total. */
  scored?: boolean
  label?: string
  detail: string
  evidence?: { url: string; kind: string; snippet: string }[]
}

const STATUS_LABEL: Record<string, string> = {
  good: 'Good',
  'needs-work': 'Needs work',
  missing: 'Not on this page',
  unverified: 'Unable to assess',
}

const STATUS_COLORS: Record<string, { bg: string; fg: string; bar: string }> = {
  good: { bg: '#dcfce7', fg: '#166534', bar: '#16a34a' },
  'needs-work': { bg: '#fef3c7', fg: '#92400e', bar: '#d97706' },
  missing: { bg: '#fee2e2', fg: '#991b1b', bar: '#dc2626' },
  unverified: { bg: '#F7F3EC', fg: '#57534E', bar: '#E7E0D6' },
}

type GeoRecommendation = {
  priority: 'high' | 'medium' | 'low'
  title: string
  description: string
  impact: string
}

type Band = 'strong' | 'adequate' | 'weak' | 'absent' | 'unverified'

type GeoAuditResult = {
  score: number
  grade: string
  breakdown: GeoFactor[]
  recommendations: GeoRecommendation[]
  quickWins: string[]
  scoreWithheld?: boolean
  withheldReason?: string
  rawScore?: number
  assessedMaxScore?: number
  pagesInspected?: { url: string; ok: boolean }[]
  /** Phase B. Absent on reports stored before the two-score model shipped. */
  retrievability?: {
    score: number
    scoreWithheld: boolean
    groups: { id: string; name: string; score: number; maxScore: number; deduction: number; scored: boolean; label: string }[]
  }
  citability?: { band: Band; label: string; signals: { id: string; name: string; band: Band; detail: string }[] }
  gap?: { quadrant: string; headline: string; diagnosis: string; nextStep: string }
}

const BAND_COLOR: Record<Band, string> = {
  strong: '#16a34a',
  adequate: '#B87333',
  weak: '#d97706',
  absent: '#dc2626',
  unverified: '#998876',
}

function isGeoResult(r: unknown): r is GeoAuditResult {
  return typeof r === 'object' && r !== null && 'score' in r && 'grade' in r && 'breakdown' in r
}

const playfair: React.CSSProperties = { fontFamily: 'var(--font-playfair, "Playfair Display", serif)' }

// ── Metadata ──────────────────────────────────────────────────────────────────

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>
}): Promise<Metadata> {
  const { token } = await params
  const supabase = createServiceClient()
  const { data } = await supabase
    .from('audit_results')
    .select('domain')
    .eq('share_token', token)
    .single()

  const domain = data?.domain ?? 'your site'
  return {
    title: `SEO Report for ${domain} — Byline`,
    description: `Audit report for ${domain} generated by Byline.`,
  }
}

// ── GEO Report ────────────────────────────────────────────────────────────────

function GeoReport({ result, domain, auditDate }: { result: GeoAuditResult; domain: string; auditDate: string }) {
  const scoreColor = result.score >= 70 ? '#16a34a' : result.score >= 40 ? '#d97706' : '#dc2626'
  const gradeColor = result.score >= 70 ? '#dcfce7' : result.score >= 40 ? '#fef3c7' : '#fee2e2'
  const gradeTextColor = result.score >= 70 ? '#166534' : result.score >= 40 ? '#92400e' : '#991b1b'

  return (
    <main style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px 80px' }}>
      {/* Header */}
      <div style={{ marginBottom: 40 }}>
        <p style={{ fontSize: 12, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.18em', color: '#B87333', marginBottom: 12 }}>
          GEO Analysis Report
        </p>
        <h1 style={{ ...playfair, fontSize: 36, fontWeight: 700, color: '#1C1917', marginBottom: 8, lineHeight: 1.1 }}>
          {domain}
        </h1>
        <p style={{ fontSize: 14, color: '#57534E', marginBottom: 24 }}>
          Analyzed on {auditDate}
        </p>

        {/* Score */}
        {result.scoreWithheld ? (
          <div style={{ background: '#fff', border: '1px solid #E7E0D6', borderRadius: 16, padding: '24px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 20, marginBottom: 12 }}>
              <div style={{
                width: 88, height: 88, borderRadius: '50%', border: '4px solid #E7E0D6',
                display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
              }}>
                <span style={{ fontSize: 28, fontWeight: 700, color: '#998876' }}>—</span>
              </div>
              <div>
                <p style={{ fontSize: 15, fontWeight: 600, color: '#1C1917', margin: 0 }}>No score published</p>
                <p style={{ fontSize: 13, color: '#998876', margin: '4px 0 0' }}>
                  A score is only published when enough of the page could be read to stand behind it.
                </p>
              </div>
            </div>
            {result.withheldReason && (
              <p style={{ fontSize: 14, color: '#57534E', background: '#F7F3EC', border: '1px solid #E7E0D6', borderRadius: 12, padding: '12px 16px', margin: 0 }}>
                {result.withheldReason}
              </p>
            )}
          </div>
        ) : (
          <div style={{ display: 'flex', alignItems: 'center', gap: 20, background: '#fff', border: '1px solid #E7E0D6', borderRadius: 16, padding: '24px' }}>
            <div style={{
              width: 88, height: 88, borderRadius: '50%', border: `4px solid ${scoreColor}`,
              display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
            }}>
              <span style={{ fontSize: 28, fontWeight: 700, color: scoreColor }}>{result.score}</span>
            </div>
            <div>
              <div style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 44, height: 44, borderRadius: 10, background: gradeColor, marginBottom: 4 }}>
                <span style={{ fontSize: 20, fontWeight: 700, color: gradeTextColor }}>{result.grade}</span>
              </div>
              <p style={{ fontSize: 14, color: '#57534E', margin: 0 }}>Content readiness score — out of 100</p>
              <p style={{ fontSize: 12, color: '#998876', margin: '2px 0 0' }}>
                {result.score >= 70 ? 'Few structural obstacles found' : result.score >= 40 ? 'Room for improvement' : 'Significant gaps to address'}
              </p>
            </div>
          </div>
        )}
      </div>

      <TwoScoreSection result={result} />

      {/* Factor breakdown */}
      {result.breakdown.length > 0 && (
        <section style={{ marginBottom: 40 }}>
          <h2 style={{ ...playfair, fontSize: 22, fontWeight: 700, color: '#1C1917', marginBottom: 16 }}>
            Factor Breakdown
          </h2>
          <div style={{ background: '#fff', border: '1px solid #E7E0D6', borderRadius: 16, padding: '20px 24px' }}>
            {result.breakdown.map((factor, i) => {
              const unscored = factor.scored === false || factor.status === 'unverified'
              const colors = STATUS_COLORS[factor.status] ?? STATUS_COLORS.unverified
              const pct = unscored || !factor.maxScore ? 0 : Math.round((factor.score / factor.maxScore) * 100)
              const badgeStyle: React.CSSProperties = {
                fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 999, flexShrink: 0,
                background: colors.bg,
                color: colors.fg,
              }
              return (
                <div key={i} style={{ paddingBottom: i < result.breakdown.length - 1 ? 16 : 0, marginBottom: i < result.breakdown.length - 1 ? 16 : 0, borderBottom: i < result.breakdown.length - 1 ? '1px solid #F7F3EC' : 'none' }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 6 }}>
                    <span style={{ fontSize: 14, fontWeight: 500, color: '#1C1917' }}>{factor.name}</span>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <span style={{ fontSize: 12, color: '#998876' }}>
                        {unscored ? '—' : `${factor.score}/${factor.maxScore}`}
                      </span>
                      <span style={badgeStyle}>
                        {factor.label ?? STATUS_LABEL[factor.status] ?? factor.status}
                      </span>
                    </div>
                  </div>
                  <div style={{ height: 6, background: '#F7F3EC', borderRadius: 4, overflow: 'hidden' }}>
                    {!unscored && <div style={{ height: '100%', borderRadius: 4, background: colors.bar, width: `${pct}%` }} />}
                  </div>
                  {factor.detail && <p style={{ fontSize: 12, color: '#57534E', margin: '6px 0 0', lineHeight: 1.5 }}>{factor.detail}</p>}
                  {factor.evidence && factor.evidence.length > 0 && (
                    <ul style={{ listStyle: 'none', margin: '8px 0 0', padding: '0 0 0 12px', borderLeft: '2px solid #E7E0D6' }}>
                      {factor.evidence.slice(0, 3).map((e, j) => (
                        <li key={j} style={{ fontSize: 11, color: '#57534E', marginBottom: 4, wordBreak: 'break-word' }}>
                          <span style={{ color: '#998876', textTransform: 'uppercase', letterSpacing: '0.06em', fontSize: 10 }}>{e.kind}</span>
                          {' '}{e.snippet}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              )
            })}
          </div>
          <p style={{ fontSize: 12, color: '#998876', margin: '12px 0 0', lineHeight: 1.6 }}>
            {result.pagesInspected?.filter((p) => p.ok).length
              ? `Pages inspected: ${result.pagesInspected.filter((p) => p.ok).map((p) => p.url).join(', ')}. `
              : ''}
            This is a heuristic assessment of how ready the published content is to be read and quoted —
            not a measurement of how often AI tools currently cite this site.
          </p>
        </section>
      )}

      {/* Quick Wins */}
      {result.quickWins.length > 0 && (
        <section style={{ marginBottom: 40 }}>
          <h2 style={{ ...playfair, fontSize: 22, fontWeight: 700, color: '#1C1917', marginBottom: 16 }}>Quick Wins</h2>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
            {result.quickWins.map((win, i) => (
              <li key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 10, padding: '10px 0', borderBottom: i < result.quickWins.length - 1 ? '1px solid #E7E0D6' : 'none' }}>
                <span style={{ color: '#B87333', fontWeight: 700, fontSize: 15, marginTop: 1, flexShrink: 0 }}>✓</span>
                <span style={{ fontSize: 15, color: '#1C1917', lineHeight: 1.5 }}>{win}</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {/* Recommendations */}
      {result.recommendations.length > 0 && (
        <section style={{ marginBottom: 48 }}>
          <h2 style={{ ...playfair, fontSize: 22, fontWeight: 700, color: '#1C1917', marginBottom: 16 }}>Recommendations</h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {result.recommendations.map((rec, i) => {
              const priorityStyle: React.CSSProperties = rec.priority === 'high'
                ? { background: 'rgba(184,115,51,0.12)', color: '#9A6228' }
                : rec.priority === 'medium'
                ? { background: '#fef3c7', color: '#b45309' }
                : { background: '#F7F3EC', color: '#57534E' }
              return (
                <div key={i} style={{ background: '#fff', border: '1px solid #E7E0D6', borderRadius: 12, padding: '16px 20px' }}>
                  <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 8 }}>
                    <h3 style={{ fontSize: 15, fontWeight: 600, color: '#1C1917', margin: 0, flex: 1 }}>{rec.title}</h3>
                    <span style={{ fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 999, flexShrink: 0, marginTop: 2, ...priorityStyle }}>
                      {rec.priority}
                    </span>
                  </div>
                  <p style={{ fontSize: 14, color: '#57534E', margin: '0 0 8px', lineHeight: 1.5 }}>{rec.description}</p>
                  {rec.impact && <p style={{ fontSize: 13, color: '#B87333', fontWeight: 500, margin: 0 }}>Impact: {rec.impact}</p>}
                </div>
              )
            })}
          </div>
        </section>
      )}

      {/* CTA */}
      <div style={{ background: '#1C1917', borderRadius: 16, padding: '32px', textAlign: 'center' }}>
        <h2 style={{ ...playfair, fontSize: 22, fontWeight: 700, color: '#F7F3EC', marginBottom: 12 }}>
          Want AI to start recommending your content?
        </h2>
        <p style={{ fontSize: 15, color: '#A89070', marginBottom: 24, lineHeight: 1.6 }}>
          Byline generates publish-ready, GEO-optimized articles structured to get cited by ChatGPT, Gemini, and Perplexity.
        </p>
        <Link href="/pricing" style={{ display: 'inline-block', background: '#B87333', color: '#fff', padding: '14px 28px', borderRadius: 12, fontWeight: 600, fontSize: 15, textDecoration: 'none' }}>
          See plans →
        </Link>
      </div>
    </main>
  )
}

// ── Content Audit Report ──────────────────────────────────────────────────────

function ContentAuditReportPage({ result, domain, auditDate }: { result: ContentAuditResult; domain: string; auditDate: string }) {
  const gaps: Gap[] = result.gaps ?? []
  const quickWins: string[] = result.quickWins ?? []
  const pageCount: number = result.pageCount ?? 0
  const highPriorityCount = gaps.filter((g) => g.priority === 'high').length

  return (
    <main style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px 80px' }}>
      <div style={{ marginBottom: 40 }}>
        <p style={{ fontSize: 12, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.18em', color: '#B87333', marginBottom: 12 }}>
          Content Gap Report
        </p>
        <h1 style={{ ...playfair, fontSize: 36, fontWeight: 700, color: '#1C1917', marginBottom: 8, lineHeight: 1.1 }}>
          {domain}
        </h1>
        <p style={{ fontSize: 14, color: '#57534E', marginBottom: 24 }}>
          Audited on {auditDate} · {pageCount} pages scanned
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12 }}>
          <div style={{ background: '#fff', border: '1px solid #E7E0D6', borderRadius: 12, padding: '16px 20px' }}>
            <p style={{ fontSize: 28, fontWeight: 700, color: '#B87333', margin: 0 }}>{gaps.length}</p>
            <p style={{ fontSize: 13, color: '#57534E', margin: '4px 0 0' }}>Content Gaps</p>
          </div>
          <div style={{ background: '#fff', border: '1px solid #E7E0D6', borderRadius: 12, padding: '16px 20px' }}>
            <p style={{ fontSize: 28, fontWeight: 700, color: '#1C1917', margin: 0 }}>{highPriorityCount}</p>
            <p style={{ fontSize: 13, color: '#57534E', margin: '4px 0 0' }}>High Priority</p>
          </div>
          <div style={{ background: '#fff', border: '1px solid #E7E0D6', borderRadius: 12, padding: '16px 20px' }}>
            <p style={{ fontSize: 28, fontWeight: 700, color: '#1C1917', margin: 0 }}>{quickWins.length}</p>
            <p style={{ fontSize: 13, color: '#57534E', margin: '4px 0 0' }}>Quick Wins</p>
          </div>
        </div>
      </div>

      {quickWins.length > 0 && (
        <section style={{ marginBottom: 40 }}>
          <h2 style={{ ...playfair, fontSize: 22, fontWeight: 700, color: '#1C1917', marginBottom: 16 }}>Quick Wins</h2>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
            {quickWins.map((win, i) => (
              <li key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 10, padding: '10px 0', borderBottom: i < quickWins.length - 1 ? '1px solid #E7E0D6' : 'none' }}>
                <span style={{ color: '#B87333', fontWeight: 700, fontSize: 15, marginTop: 1, flexShrink: 0 }}>✓</span>
                <span style={{ fontSize: 15, color: '#1C1917', lineHeight: 1.5 }}>{win}</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {gaps.length > 0 && (
        <section style={{ marginBottom: 48 }}>
          <h2 style={{ ...playfair, fontSize: 22, fontWeight: 700, color: '#1C1917', marginBottom: 16 }}>Action Items</h2>
          <p style={{ fontSize: 14, color: '#57534E', marginBottom: 20 }}>
            Each item below is a specific article you should write.
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {gaps.map((gap, i) => (
              <div key={i} style={{ background: '#fff', border: '1px solid #E7E0D6', borderRadius: 12, padding: '16px 20px' }}>
                <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 8 }}>
                  <h3 style={{ fontSize: 15, fontWeight: 600, color: '#1C1917', margin: 0, flex: 1 }}>
                    Write an article targeting &ldquo;{gap.suggestedKeyword || gap.title}&rdquo;
                  </h3>
                  {gap.priority === 'high' && (
                    <span style={{ fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 999, background: 'rgba(184,115,51,0.12)', color: '#9A6228', flexShrink: 0, marginTop: 2 }}>
                      High Priority
                    </span>
                  )}
                  {gap.priority === 'medium' && (
                    <span style={{ fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 999, background: 'rgba(217,119,6,0.1)', color: '#b45309', flexShrink: 0, marginTop: 2 }}>
                      Medium
                    </span>
                  )}
                </div>
                <p style={{ fontSize: 14, color: '#57534E', margin: '0 0 8px', lineHeight: 1.5 }}>{gap.description}</p>
                <p style={{ fontSize: 13, color: '#B87333', fontWeight: 500, margin: 0 }}>Topic: {gap.title}</p>
              </div>
            ))}
          </div>
        </section>
      )}

      <div style={{ background: '#1C1917', borderRadius: 16, padding: '32px', textAlign: 'center' }}>
        <h2 style={{ ...playfair, fontSize: 22, fontWeight: 700, color: '#F7F3EC', marginBottom: 12 }}>
          Want Byline to write these articles for you?
        </h2>
        <p style={{ fontSize: 15, color: '#A89070', marginBottom: 24, lineHeight: 1.6 }}>
          Byline generates publish-ready, SEO-optimized articles from your content gaps — in your brand voice, in minutes.
        </p>
        <Link href="/pricing" style={{ display: 'inline-block', background: '#B87333', color: '#fff', padding: '14px 28px', borderRadius: 12, fontWeight: 600, fontSize: 15, textDecoration: 'none' }}>
          See plans →
        </Link>
      </div>
    </main>
  )
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default async function ReportPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const supabase = createServiceClient()

  const { data, error } = await supabase
    .from('audit_results')
    .select('id, domain, result, created_at, url')
    .eq('share_token', token)
    .single()

  const nav = (
    <nav style={{ background: '#FDFAF6', borderBottom: '1px solid #E7E0D6', padding: '0 24px', position: 'sticky', top: 0, zIndex: 50 }}>
      <div style={{ maxWidth: 960, margin: '0 auto', height: 56, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <Link href="/">
          <span style={{ ...playfair, fontSize: 22, fontWeight: 900, color: '#B87333', letterSpacing: '-0.01em' }}>
            byline<span style={{ color: '#1C1917' }}>.</span>
          </span>
        </Link>
        <span style={{ fontSize: 13, color: '#57534E' }}>Audit Report</span>
      </div>
    </nav>
  )

  if (error || !data) {
    return (
      <div style={{ background: '#FDFAF6', minHeight: '100vh', color: '#1C1917' }}>
        {nav}
        <div style={{ maxWidth: 640, margin: '80px auto', padding: '0 24px', textAlign: 'center' }}>
          <h1 style={{ ...playfair, fontSize: 32, fontWeight: 700, color: '#1C1917', marginBottom: 16 }}>Report not found</h1>
          <p style={{ fontSize: 16, color: '#57534E', marginBottom: 32 }}>This report link may have expired or the URL is incorrect.</p>
          <Link href="/audit" style={{ display: 'inline-block', background: '#B87333', color: '#fff', padding: '12px 24px', borderRadius: 12, fontWeight: 600, fontSize: 15, textDecoration: 'none' }}>
            Run a new audit →
          </Link>
        </div>
      </div>
    )
  }

  const domain = data.domain ?? (data.url ? new URL(data.url.startsWith('http') ? data.url : `https://${data.url}`).hostname : 'your site')
  const auditDate = new Date(data.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const result = data.result

  return (
    <div style={{ background: '#FDFAF6', minHeight: '100vh', color: '#1C1917' }}>
      {nav}
      {isGeoResult(result)
        ? <GeoReport result={result} domain={domain} auditDate={auditDate} />
        : <ContentAuditReportPage result={result as ContentAuditResult} domain={domain} auditDate={auditDate} />
      }
    </div>
  )
}
